apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rgraphql-demo-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rgraphql-demo-server
        tier: backend
    spec:
      containers:
      - name: rgraphql-demo-server
        image: paralin/rgraphql-demo-server:latest
        ports:
        - containerPort: 3001
