apiVersion: v1
kind: Service
metadata:
  labels:
    app: rgraphql-demo-server
    tier: backend
  name: rgraphql-demo-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: rgraphql-demo-server
  type: LoadBalancer
